# Generated by Django 5.2.1 on 2025-05-29 14:39

import meta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_description', models.TextField()),
                ('logo', models.ImageField(upload_to='site/')),
                ('contact_mobile', models.CharField(blank=True, max_length=11)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.TextField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('_meta_title', models.CharField(blank=True, max_length=200)),
                ('_meta_description', models.TextField(blank=True)),
                ('_meta_keywords', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'site setting',
                'verbose_name_plural': 'site settings',
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
    ]
