# Generated by Django 5.2.1 on 2025-05-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_title_product_name_and_more'),
        ('shop', '0003_add_attributes'),
    ]

    operations = [
    ]
