# Generated by Django 5.2.1 on 2025-05-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_discountcode_discountusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'discount code', 'verbose_name_plural': 'discount codes'},
        ),
        migrations.AlterModelOptions(
            name='discountusage',
            options={'verbose_name': 'discount usage', 'verbose_name_plural': 'discount usages'},
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='allowed_emails',
            field=models.TextField(blank=True, help_text='Allowed emails (one email per line)'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'درصدی'), ('fixed_cart', 'ثابت سبد خرید'), ('fixed_product', 'ثابت محصول')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='exclude_sale_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='excluded_categories',
            field=models.ManyToManyField(blank=True, related_name='excluded_discount_codes', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excluded_discount_codes', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='individual_use_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='discount_codes', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='discount_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='shop.discountcode'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='used_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discountusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL),
        ),
    ]
